# Generated by Django 3.0.7 on 2020-06-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(blank=True, null=True)),
                ('queue', models.IntegerField(default=0)),
                ('tid', models.CharField(max_length=32)),
                ('errormsg', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('finish_ts', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[(0, 'Queued'), (1, 'Running'), (2, 'Completed'), (3, 'Failed')], default=0, max_length=1)),
            ],
        ),
    ]
